#!/usr/bin/env bash
#commenttttttttttttttttttttttttttttttt
echo "http {

    server {
        listen 80;
        server_name 472055-web-01;

        location / {
            add_header X-Served-By \"472055-web-01\";
        }
    }

    server {
        listen 80;
        server_name 472055-web-02;

        location / {
            add_header X-Served-By \"472055-web-02\";
        }
    }

    upstream backend_server1 {
        server 472055-web-01:80;
    }

    upstream backend_server2 {
        server 472055-web-02:80;
    }

}" | sudo tee -a /etc/nginx/nginx.conf > /dev/null
sudo systemctl reload nginx
