#!/usr/bin/env bash
#commenttttttttttttttttttttttttttttttt
sudo apt-get -y update;
sudo apt-get -y install nginx;
sudo ufw allow 'Nginx HTTP';
sudo chmod -R 755 /var/www;
echo "http {
    server {
        listen 80;
        server_name 472055-web-01;

        location / {
            add_header X-Served-By \"472055-web-01\";
        }
    }

    upstream backend_server1 {
        server 472055-web-01:80;
    }
}" | sudo tee /etc/nginx/sites-available/web-01 > /dev/null;
sudo ln -s /etc/nginx/sites-available/web-01 /etc/nginx/sites-enabled/;
sudo systemctl reload nginx;
echo "http {
    server {
        listen 80;
        server_name 472055-web-02;

        location / {
            add_header X-Served-By \"472055-web-02\";
        }
    }

    upstream backend_server2 {
        server 472055-web-02:80;
    }
}" | sudo tee /etc/nginx/sites-available/web-02 > /dev/null;
sudo ln -s /etc/nginx/sites-available/web-02 /etc/nginx/sites-enabled/;
sudo sudo service nginx reload;
