#!/usr/bin/env bash
#commentttttttttttttttttttttttttttttttttttt

school="./school"
if [ -e "$school" ]; then
    echo "school file exists"
	if [ ! -s "$school" ]; then
	    echo "school file is empty"
	elif [ -s "$school" ]; then
	    echo "school file is not empty"
		if [ -f "$school" ]; then
	        echo "school is a regular file"
	    fi
	fi
else
    echo "school file does not exist"
fi
