#!/usr/bin/env bash
#commenttttttttttttttttttttttttttt
sudo apt update
sudo apt -y install ufw
sudo ufw disable
sudo ufw default deny incoming
sudo ufw default deny outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
