#!/usr/bin/env bash
#commentttttttttttttttttttttttttttttttttttt
echo "<VirtualHost *:8080>
    DocumentRoot /var/www/html
    ServerName localhost
</VirtualHost>" >> /etc/apache2/apache2.conf
sudo service apache2 restart
